### ISSUE TITLE
controller describe-stream <scope-name> <stream-name> is throwing InterruptedException

### ISSUE THREAD

**Issue by Richa-Srivastava** [pravega/pravega-tools#22]
Pravega-cli is giving error rather than correct output for the command:
` controller describe-stream <scope-name> <stream-name>`
```
> controller describe-stream longevity mediumScale
ERROR [2019-05-06 10:50:25.950] [Curator-Framework-0] o.a.c.f.imps.CuratorFrameworkImpl: Background exception was not retry-able or retry gave up
java.lang.InterruptedException: null
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at org.apache.zookeeper.ClientCnxn.submitRequest(ClientCnxn.java:1499)
        at org.apache.zookeeper.ClientCnxn.submitRequest(ClientCnxn.java:1487)
        at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:1904)
        at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:1937)
        at org.apache.curator.utils.ZKPaths.mkdirs(ZKPaths.java:274)
        at org.apache.curator.framework.imps.CreateBuilderImpl$9.performBackgroundOperation(CreateBuilderImpl.java:799)
        at org.apache.curator.framework.imps.OperationAndData.callPerformBackgroundOperation(OperationAndData.java:84)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:947)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.backgroundOperationsLoop(CuratorFrameworkImpl.java:925)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.access$300(CuratorFrameworkImpl.java:73)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl$4.call(CuratorFrameworkImpl.java:322)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Exception accessing the metadata store: java.util.concurrent.CompletionException: io.pravega.controller.store.stream.StoreException$DataNotFoundException: /store/longevity/mediumScale/configuration
```
Build details are:
```
Pravega version: 0.5.0-2236.5228e2d
Zookeeper Operator : pravega/zookeeper-operator:0.2.1
Pravega Operator: pravega/pravega-operator:0.3.2
```

**Comment by RaulGracia** [comment]
@Richa-Srivastava, could you use the branch in #29 and check if it works now for you? Thanks!

**Comment by Richa-Srivastava** [comment]
@RaulGracia please find the verification result :
https://github.com/pravega/pravega-tools/issues/30

**Comment by Richa-Srivastava** [comment]
As per verification: https://github.com/pravega/pravega-tools/issues/30
@RaulGracia this issue is still reproducible for me, please find the details:
```
> controller list-streams longevity
Successful REST request.
{
  "streams": [
    {
      "scopeName": "longevity",
      "streamName": "mediumScale",
      "scalingPolicy": {
        "type": "BY_RATE_IN_EVENTS_PER_SEC",
        "targetRate": 200,
        "scaleFactor": 2,
        "minSegments": 4
      },
      "retentionPolicy": {
        "type": "LIMITED_DAYS",
        "value": 0
      }
    }
  ]
}

> controller describe-stream longevity mediumScale
Exception accessing the metadata store: io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.pravega.controller.store.stream.StoreException$StoreConnectionException: get entry: key: longevity table: _system/_tables/scopes
```
Following is my conf.properties file:
```
root@pravega-benchmark:/pravega-cli_2269# cat conf/config.properties 
#
# Copyright (c) 2017 Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#

# Config for CLI credentials (at the moment, Controller auth is only supported).
cli.authEnabled=false
cli.userName=admin
cli.password=1111_aaaa

# Config for CLI Controller REST/GRPC endpoints.
cli.controllerRestUri=http://10.100.200.224:10080
cli.controllerGrpcUri=tcp://10.100.200.224:9090
cli.metadataBackend=segmentstore

# General configuration for the Pravega cluster at hand.
pravegaservice.clusterName=pravega
pravegaservice.containerCount=4

# Config for Zookeeper service.
pravegaservice.zkURL=pravega-zk-client:2181

# Config for Bookkeeper commands.
bookkeeper.bkLedgerPath=/pravega/pravega/bookkeeper/ledgers
```

**Comment by sumit-bm** [comment]
Based on the above comment from @Richa-Srivastava re-opening the issue.

**Comment by Richa-Srivastava** [comment]
Working as expected after providing IPs from `kubectl describe po <pod-name>` inside `config.properties`:
```
 controller describe-stream longevity mediumScale
{
  "key": "stream_config",
  "value": {
    "scalingPolicy": {
      "scaleType": "BY_RATE_IN_EVENTS_PER_SEC",
      "targetRate": 200,
      "scaleFactor": 2,
      "minNumSegments": 4
    },
    "retentionPolicy": {
      "retentionType": "TIME",
      "retentionParam": 3600000
    }
  }
}
{
  "key": "stream_state",
  "value": "ACTIVE"
}
{
  "key": "segment_count",
  "value": 136
}
{
  "key": "is_sealed",
  "value": false
}
{
  "key": "active_epoch",
  "value": {
    "epoch": 159,
    "referenceEpoch": 159,
    "segments": [
      {
        "segmentNumber": 217,
        "creationEpoch": 133,
        "creationTime": 1560330114136,
        "keyStart": 0.23828125,
        "keyEnd": 0.265625
      },
      {
        "segmentNumber": 221,
        "creationEpoch": 136,
        "creationTime": 1560330412303,
        "keyStart": 0.9267578125,
        "keyEnd": 1.0
      },
      {
        "segmentNumber": 226,
        "creationEpoch": 139,
        "creationTime": 1560330694613,
        "keyStart": 0.55078125,
        "keyEnd": 0.6015625
      },
      {
        "segmentNumber": 227,
        "creationEpoch": 140,
        "creationTime": 1560330774624,
        "keyStart": 0.873046875,
        "keyEnd": 0.89990234375
      },
      {
        "segmentNumber": 228,
        "creationEpoch": 140,
        "creationTime": 1560330774624,
        "keyStart": 0.89990234375,
        "keyEnd": 0.9267578125
      },
      {
        "segmentNumber": 237,
        "creationEpoch": 149,
        "creationTime": 1560331653710,
        "keyStart": 0.671875,
        "keyEnd": 0.7109375
      },
      {
        "segmentNumber": 238,
        "creationEpoch": 149,
        "creationTime": 1560331653710,
        "keyStart": 0.7109375,
        "keyEnd": 0.75
      },
      {
        "segmentNumber": 239,
        "creationEpoch": 150,
        "creationTime": 1560331655765,
        "keyStart": 0.0625,
        "keyEnd": 0.109375
      },
      {
        "segmentNumber": 240,
        "creationEpoch": 151,
        "creationTime": 1560331673596,
        "keyStart": 0.34375,
        "keyEnd": 0.4140625
      },
      {
        "segmentNumber": 241,
        "creationEpoch": 152,
        "creationTime": 1560331675668,
        "keyStart": 0.48046875,
        "keyEnd": 0.515625
      },
      {
        "segmentNumber": 242,
        "creationEpoch": 152,
        "creationTime": 1560331675668,
        "keyStart": 0.515625,
        "keyEnd": 0.55078125
      },
      {
        "segmentNumber": 243,
        "creationEpoch": 153,
        "creationTime": 1560331913049,
        "keyStart": 0.6015625,
        "keyEnd": 0.671875
      },
      {
        "segmentNumber": 244,
        "creationEpoch": 154,
        "creationTime": 1560331915902,
        "keyStart": 0.4140625,
        "keyEnd": 0.447265625
      },
      {
        "segmentNumber": 245,
        "creationEpoch": 154,
        "creationTime": 1560331915902,
        "keyStart": 0.447265625,
        "keyEnd": 0.48046875
      },
      {
        "segmentNumber": 246,
        "creationEpoch": 155,
        "creationTime": 1560331918272,
        "keyStart": 0.0,
        "keyEnd": 0.03125
      },
      {
        "segmentNumber": 247,
        "creationEpoch": 155,
        "creationTime": 1560331918272,
        "keyStart": 0.03125,
        "keyEnd": 0.0625
      },
      {
        "segmentNumber": 248,
        "creationEpoch": 156,
        "creationTime": 1560331918291,
        "keyStart": 0.75,
        "keyEnd": 0.8115234375
      },
      {
        "segmentNumber": 249,
        "creationEpoch": 156,
        "creationTime": 1560331918291,
        "keyStart": 0.8115234375,
        "keyEnd": 0.873046875
      },
      {
        "segmentNumber": 250,
        "creationEpoch": 157,
        "creationTime": 1560331920904,
        "keyStart": 0.16015625,
        "keyEnd": 0.19921875
      },
      {
        "segmentNumber": 251,
        "creationEpoch": 157,
        "creationTime": 1560331920904,
        "keyStart": 0.19921875,
        "keyEnd": 0.23828125
      },
      {
        "segmentNumber": 252,
        "creationEpoch": 158,
        "creationTime": 1560331922987,
        "keyStart": 0.109375,
        "keyEnd": 0.134765625
      },
      {
        "segmentNumber": 253,
        "creationEpoch": 158,
        "creationTime": 1560331922987,
        "keyStart": 0.134765625,
        "keyEnd": 0.16015625
      },
      {
        "segmentNumber": 254,
        "creationEpoch": 159,
        "creationTime": 1560331974984,
        "keyStart": 0.265625,
        "keyEnd": 0.3046875
      },
      {
        "segmentNumber": 255,
        "creationEpoch": 159,
        "creationTime": 1560331974984,
        "keyStart": 0.3046875,
        "keyEnd": 0.34375
      }
    ],
    "creationTime": 1560331974984,
    "duplicate": false,
    "segmentIds": [
      682899800319,
      682899800318,
      678604833020,
      678604833021,
      670014898424,
      670014898425,
      674309865723,
      674309865722,
      648540061936,
      601295421668,
      652835029233,
      597000454370,
      657129996531,
      652835029234,
      665719931127,
      665719931126,
      661424963828,
      661424963829,
      601295421667,
      584115552477,
      639950127341,
      644245094639,
      639950127342,
      571230650585
    ]
  }
}
{
  "key": "truncation_record",
  "value": {
    "streamCut": {
      "347892351112": 110277703,
      "326417514623": 167869929,
      "339302416517": 80342237,
      "330712481921": 145904225,
      "326417514624": 121607180,
      "322122547326": 168413774,
      "343597383814": 68291846,
      "339302416516": 103301493,
      "313532612729": 220854819,
      "317827580028": 145874132,
      "352187318411": 77155912,
      "214748364890": 325712956,
      "335007449219": 150217650,
      "343597383815": 79864358,
      "356482285708": 87986892,
      "347892351113": 132931219,
      "360777253006": 43770938,
      "360777253007": 121096841,
      "352187318410": 77322802,
      "365072220304": 58687687,
      "330712481922": 131015369,
      "322122547325": 182934516,
      "356482285709": 54784101,
      "283467841648": 219594035,
      "365072220305": 26029391,
      "369367187602": 98696660,
      "317827580027": 199487743
    },
    "span": {
      "StreamSegmentRecord(segmentNumber=136, creationEpoch=81, creationTime=1560326252586, keyStart=0.875, keyEnd=0.90234375)": 86,
      "StreamSegmentRecord(segmentNumber=127, creationEpoch=76, creationTime=1560325916667, keyStart=0.0, keyEnd=0.03125)": 86,
      "StreamSegmentRecord(segmentNumber=133, creationEpoch=79, creationTime=1560326218525, keyStart=0.6015625, keyEnd=0.625)": 86,
      "StreamSegmentRecord(segmentNumber=128, creationEpoch=76, creationTime=1560325916667, keyStart=0.03125, keyEnd=0.0625)": 86,
      "StreamSegmentRecord(segmentNumber=129, creationEpoch=77, creationTime=1560325966787, keyStart=0.265625, keyEnd=0.3046875)": 86,
      "StreamSegmentRecord(segmentNumber=134, creationEpoch=80, creationTime=1560326223046, keyStart=0.109375, keyEnd=0.1328125)": 86,
      "StreamSegmentRecord(segmentNumber=126, creationEpoch=75, creationTime=1560325914739, keyStart=0.671875, keyEnd=0.71875)": 86,
      "StreamSegmentRecord(segmentNumber=132, creationEpoch=79, creationTime=1560326218525, keyStart=0.578125, keyEnd=0.6015625)": 86,
      "StreamSegmentRecord(segmentNumber=121, creationEpoch=73, creationTime=1560325655224, keyStart=0.46875, keyEnd=0.5234375)": 86,
      "StreamSegmentRecord(segmentNumber=139, creationEpoch=82, creationTime=1560326254540, keyStart=0.0859375, keyEnd=0.109375)": 86,
      "StreamSegmentRecord(segmentNumber=124, creationEpoch=74, creationTime=1560325675102, keyStart=0.4375, keyEnd=0.46875)": 86,
      "StreamSegmentRecord(segmentNumber=131, creationEpoch=78, creationTime=1560326212107, keyStart=0.34375, keyEnd=0.40625)": 86,
      "StreamSegmentRecord(segmentNumber=90, creationEpoch=50, creationTime=1560323851651, keyStart=0.71875, keyEnd=0.75)": 86,
      "StreamSegmentRecord(segmentNumber=135, creationEpoch=80, creationTime=1560326223046, keyStart=0.1328125, keyEnd=0.15625)": 86,
      "StreamSegmentRecord(segmentNumber=140, creationEpoch=83, creationTime=1560326256638, keyStart=0.8125, keyEnd=0.84375)": 86,
      "StreamSegmentRecord(segmentNumber=137, creationEpoch=81, creationTime=1560326252586, keyStart=0.90234375, keyEnd=0.9296875)": 86,
      "StreamSegmentRecord(segmentNumber=142, creationEpoch=84, creationTime=1560326258638, keyStart=0.75, keyEnd=0.78125)": 86,
      "StreamSegmentRecord(segmentNumber=143, creationEpoch=84, creationTime=1560326258638, keyStart=0.78125, keyEnd=0.8125)": 86,
      "StreamSegmentRecord(segmentNumber=138, creationEpoch=82, creationTime=1560326254540, keyStart=0.0625, keyEnd=0.0859375)": 86,
      "StreamSegmentRecord(segmentNumber=144, creationEpoch=85, creationTime=1560326619029, keyStart=0.5234375, keyEnd=0.55078125)": 86,
      "StreamSegmentRecord(segmentNumber=130, creationEpoch=77, creationTime=1560325966787, keyStart=0.3046875, keyEnd=0.34375)": 86,
      "StreamSegmentRecord(segmentNumber=125, creationEpoch=75, creationTime=1560325914739, keyStart=0.625, keyEnd=0.671875)": 86,
      "StreamSegmentRecord(segmentNumber=141, creationEpoch=83, creationTime=1560326256638, keyStart=0.84375, keyEnd=0.875)": 86,
      "StreamSegmentRecord(segmentNumber=145, creationEpoch=85, creationTime=1560326619029, keyStart=0.55078125, keyEnd=0.578125)": 86,
      "StreamSegmentRecord(segmentNumber=112, creationEpoch=66, creationTime=1560325369334, keyStart=0.9296875, keyEnd=1.0)": 86,
      "StreamSegmentRecord(segmentNumber=146, creationEpoch=86, creationTime=1560326851105, keyStart=0.15625, keyEnd=0.265625)": 86,
      "StreamSegmentRecord(segmentNumber=123, creationEpoch=74, creationTime=1560325675102, keyStart=0.40625, keyEnd=0.4375)": 86
    },
    "spanEpochLow": 86,
    "spanEpochHigh": 86,
    "deletedSegments": [
      3,
      8589934598,
      17179869195,
      4294967300,
      12884901897,
      0,
      17179869194,
      4294967301,
      1,
      2,
      8589934599,
      12884901896,
      85899345962,
      81604378665,
      51539607579,
      42949672983,
      30064771089,
      77309411366,
      103079215154,
      94489280559,
      25769803791,
      90194313261,
      98784247856,
      21474836493,
      73014444068,
      68719476771,
      81604378664,
      55834574877,
      77309411367,
      21474836492,
      94489280558,
      30064771088,
      64424509472,
      38654705685,
      25769803790,
      42949672982,
      85899345963,
      47244640281,
      68719476770,
      34359738386,
      51539607578,
      98784247857,
      60129542175,
      73014444069,
      55834574876,
      47244640280,
      90194313260,
      34359738387,
      103079215155,
      38654705684,
      223338299484,
      180388626505,
      184683593804,
      193273528400,
      163208757317,
      197568495697,
      107374182453,
      206158430294,
      188978561101,
      201863462996,
      146028888129,
      128849018941,
      60129542174,
      124554051644,
      115964117048,
      137438953535,
      120259084347,
      107374182452,
      214748364889,
      176093659208,
      210453397591,
      193273528399,
      150323855426,
      197568495698,
      64424509473,
      188978561102,
      158913790020,
      154618822723,
      210453397592,
      111669149750,
      141733920832,
      115964117049,
      133143986238,
      201863462995,
      184683593803,
      120259084346,
      111669149751,
      167503724614,
      206158430293,
      227633266781,
      261993005163,
      227633266782,
      219043332187,
      244813135974,
      287762808945,
      171798691911,
      279172874351,
      249108103271,
      274877907054,
      236223201377,
      257698037866,
      240518168675,
      180388626506,
      292057776242,
      296352743540,
      231928234080,
      300647710837,
      313532612730,
      266287972460,
      253403070569,
      236223201378,
      240518168676,
      270582939757,
      292057776243,
      309237645432,
      231928234079,
      309237645431,
      244813135973,
      249108103272,
      304942678134
    ],
    "toDelete": [],
    "sizeTill": 22775043999,
    "updating": false
  }
}
{
  "key": "scaling_info",
  "value": [
    {
      "timestamp": 1560319945272,
      "segments": [
        {
          "number": 0,
          "epoch": 0,
          "start": 1560319945272,
          "keyStart": 0.0,
          "keyEnd": 0.25
        },
        {
          "number": 1,
          "epoch": 0,
          "start": 1560319945272,
          "keyStart": 0.25,
          "keyEnd": 0.5
        },
        {
          "number": 2,
          "epoch": 0,
          "start": 1560319945272,
          "keyStart": 0.5,
          "keyEnd": 0.75
        },
        {
          "number": 3,
          "epoch": 0,
          "start": 1560319945272,
          "keyStart": 0.75,
          "keyEnd": 1.0
        }
      ],
      "splits": 0,
      "merges": 0
    }
  ]
}
```
