### ISSUE TITLE
bk list throws "BKException$ZKException"

### ISSUE THREAD

**Issue by SomeshJoshi19** [pravega/pravega-tools#23]
Pravega-cli command "bk list" throws following ERROR when used over Pravega-cluster instead of giving bookie log list 
```
> bk list
ERROR [2019-05-06 11:25:58.262] [main] o.a.bookkeeper.client.BookieWatcher: Failed to get bookie list : 
org.apache.bookkeeper.client.BKException$ZKException: Error while using ZooKeeper
        at org.apache.bookkeeper.discover.ZKRegistrationClient.lambda$getChildren$0(ZKRegistrationClient.java:212)
        at org.apache.bookkeeper.zookeeper.ZooKeeperClient$25$1.processResult(ZooKeeperClient.java:1174)
        at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:619)
        at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:499)
io.pravega.segmentstore.storage.DataLogNotAvailableException: Unable to establish connection to ZooKeeper or BookKeeper.
        at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLogFactory.initialize(BookKeeperLogFactory.java:96)
        at io.pravega.tools.pravegacli.commands.bookkeeper.BookKeeperCommand.createContext(BookKeeperCommand.java:67)
        at io.pravega.tools.pravegacli.commands.bookkeeper.BookKeeperListCommand.execute(BookKeeperListCommand.java:35)
        at io.pravega.tools.pravegacli.AdminRunner.execCommand(AdminRunner.java:123)
        at io.pravega.tools.pravegacli.AdminRunner.processCommand(AdminRunner.java:110)
        at io.pravega.tools.pravegacli.AdminRunner.interactiveMode(AdminRunner.java:92)
        at io.pravega.tools.pravegacli.AdminRunner.main(AdminRunner.java:76)
Caused by: org.apache.bookkeeper.client.BKException$ZKException: Error while using ZooKeeper
        at org.apache.bookkeeper.discover.ZKRegistrationClient.lambda$getChildren$0(ZKRegistrationClient.java:212)
        at org.apache.bookkeeper.zookeeper.ZooKeeperClient$25$1.processResult(ZooKeeperClient.java:1174)
        at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:619)
        at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:499)
```

**Comment by sumit-bm** [comment]
@SomeshJoshi19 could you check `config.properties` if properly updated according to deployment?

**Comment by RaulGracia** [comment]
@SomeshJoshi19 have you correctly configured the CLI? Note that you need to change the `pravegaservice.cluster-name` parameter as well as the `bookkeeper.bkLedgerPath` with the right cluster name.

**Comment by RaulGracia** [comment]
Closing this issue, as it points to a configuration problem and @SomeshJoshi19 has not reproduced it yet. If you find this problem again, please re-open the issue.
