### ISSUE TITLE
Exception thrown while doing `bk cleanup` 

### ISSUE THREAD

**Issue by Richa-Srivastava** [pravega/pravega-tools#27]
Following Exception was thrown when tried executing `bk cleanup`, having 4 bookkeeper pods:
```
> bk cleanup 
Searching for all the ledgers ...
Searching for all referenced ledgers ...
Searching for possible other BookKeeperLogs ...
java.lang.Exception: Discovered BookKeeperLog 4 which is beyond the maximum log id (3) as specified in the configuration.
        at io.pravega.tools.pravegacli.commands.bookkeeper.BookKeeperCleanupCommand.checkForExtraLogs(BookKeeperCleanupCommand.java:143)
        at io.pravega.tools.pravegacli.commands.bookkeeper.BookKeeperCleanupCommand.execute(BookKeeperCleanupCommand.java:65)
        at io.pravega.tools.pravegacli.AdminRunner.execCommand(AdminRunner.java:123)
        at io.pravega.tools.pravegacli.AdminRunner.processCommand(AdminRunner.java:110)
        at io.pravega.tools.pravegacli.AdminRunner.interactiveMode(AdminRunner.java:92)
        at io.pravega.tools.pravegacli.AdminRunner.main(AdminRunner.java:76)
```
Following is the pod details:
```
kubectl get po
NAME                                                 READY     STATUS    RESTARTS   AGE
pravega-benchmark                                    1/1       Running   0          11d
pravega-bookie-0                                     1/1       Running   0          3h
pravega-bookie-1                                     1/1       Running   0          3h
pravega-bookie-2                                     1/1       Running   0          3h
pravega-bookie-3                                     1/1       Running   0          3h
pravega-operator-779879b48-t52gd                     1/1       Running   0          5d
pravega-pravega-controller-6dd4686578-tbwsv          1/1       Running   0          5d
pravega-pravega-controller-6dd4686578-zrqvg          1/1       Running   0          3d
pravega-pravega-segmentstore-0                       1/1       Running   0          3h
pravega-pravega-segmentstore-1                       1/1       Running   0          3h
pravega-pravega-segmentstore-2                       1/1       Running   0          3h
pravega-zk-0                                         1/1       Running   0          5d
pravega-zk-1                                         1/1       Running   0          5d
pravega-zk-2                                         1/1       Running   0          5d
pravega-zk-3                                         1/1       Running   0          4d
shaka-zulu-nfs-client-provisioner-59d7f8f84c-drq5q   1/1       Running   0          5d
zookeeper-operator-685bfcbbc5-l4fxs                  1/1       Running   0          5d

```

**Comment by andreipaduroiu** [comment]
This is because the CLI config lists 4 containers, but the cluster has more than 4. The solution to this is to either set your container count in the config file you use, or set it in the CLI itself or @RaulGracia can add a feature to get this from the controller.

**Comment by RaulGracia** [comment]
As @andreipaduroiu commented, the number of containers can be re-set by using `config set pravegaservice.containerCount=[NUM OF CONTAINERS]`. I think that this may be enough to handle this situation.
